blog/urls.py
from django.urls import path

from blog.views import (PostView, PostCreate, PostUpdate, 
                        PostDelete, CommentCreate, home)

app_name = 'blog'
urlpatterns = [
    # ex: /blog/
    path('', home, name='home'),
    # ex: /blog/dusan
    path('<str:username>', home, name='user_posts'),
    # # ex: /blog/post/5/
    path('post/<int:pk>/', PostView.as_view(), name='post'),
    # # ex: /blog/post/create/
    path('post/create/', PostCreate.as_view(), name='create_post'),
    # # ex: /blog/post/5/update/
    path('post/create/<int:pk>/update', PostUpdate.as_view(), name='update_post'),
    # # ex: /blog/post/5/delete/
    path('post/<int:pk>/delete/', PostDelete.as_view(), name='delete_post'),
    # # ex: /blog/post/5/comment/
    path('post/<int:pk>/comment/', CommentCreate.as_view(), name='create_comment')
]

demo/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from blog.views import RegisterView

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='blog/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='blog:home')),
    path('register/', RegisterView.as_view(), name='register'),
    path('', include('django.contrib.auth.urls'))
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=80)
    body = models.TextField()
    pub_date = models.DateTimeField('date published', auto_now_add=True)

    def get_absolute_url(self):
        return reverse('blog:post', kwargs={'pk': self.pk})

    def __str__(self):
        return '"{title}" by {username}'.format(title=self.title,
                                                username=self.user.username)

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    body = models.TextField()
    pub_date = models.DateTimeField('date published', auto_now_add=True)

    def __str__(self):
        return '"{body}..." on {post_title} by {username}'.format(body=self.body[:20],
                                                                  post_title=self.post.title,
                                                                  username=self.user.username)

blog/views.py
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.shortcuts import render,get_object_or_404
from blog.models import Post,Comment
from django.contrib.auth.hashers import make_password
from django.urls import reverse_lazy,reverse
from django.views import generic
from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


# Create your views here.

NUM_OF_POSTS = 5



def home(request, username=None):
    first_name = ''
    last_name = ''
    if username:
        user = get_object_or_404(User,username=username)
        first_name = user.first_name
        last_name = user.last_name
        post_list = Post.objects.filter(user=user)
    else:
        post_list = Post.objects.all()

    post_list = post_list.order_by('-pub_date')

    paginator = Paginator(post_list, NUM_OF_POSTS)  # Show NUM_OF_PAGES posts per page
    page = request.GET.get('page')

    posts = paginator.get_page(page)

    return render(request, 'blog/home.html', {'posts': posts,
                                              'first_name': first_name,
                                              'last_name': last_name})
    
class RegisterView(CreateView):
    model = User
    fields = ['username', 'password', 'first_name', 'last_name', 'email']
    template_name = 'blog/registration.html'
    success_url = reverse_lazy('login')

    def form_valid(self, form):
        # Hash password before sending it to super
        form.instance.password = make_password(form.instance.password)
        return super().form_valid(form)
class PostView(generic.DetailView):
    model = Post
    template_name = 'blog/post.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in the username
        comments = Comment.objects.filter(post=self.kwargs['pk'])
        context['comments'] = comments
        return context


class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'body']
    template_name = 'blog/create_post.html'
    login_url = reverse_lazy('login')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class PostUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'body']
    template_name = 'blog/create_post.html'
    login_url = reverse_lazy('login')

    def test_func(self):
        return Post.objects.get(id=self.kwargs['pk']).user == self.request.user


class PostDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:home')
    login_url = reverse_lazy('login')

    def test_func(self):
        return Post.objects.get(id=self.kwargs['pk']).user == self.request.user


class CommentCreate(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ['body']
    template_name = 'blog/create_comment.html'
    login_url = reverse_lazy('login')

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.post = Post.objects.get(id=self.kwargs['pk'])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:post', kwargs={'pk': self.kwargs['pk']})

blog/templates/blog/base.html
<!-- this is base template with navbar and footer -->
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Django Blog</title>

    <link href="http://cdn.jsdelivr.net/webjars/bootstrap/3.3.4/css/bootstrap.min.css"
          rel="stylesheet" media="screen"/>
    <script src="http://cdn.jsdelivr.net/webjars/jquery/2.1.4/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}"/>

</head>
<body>

<!-- navbar -->
<nav class="navbar navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'blog:home' %}">Blog App</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse navbar-right">
            <!-- show registration only if user is not yet authenticated -->
            {% if not user.is_authenticated %}
                <ul class="nav navbar-nav ">
                    <li class="active"><a href="{% url 'register' %}">Registration</a></li>
                </ul>
            {% endif %}
            <!-- show login only if user is not yet authenticated -->
            {% if not user.is_authenticated %}
                <ul class="nav navbar-nav ">
                    <li class="active"><a href="{% url 'login' %}">Login</a></li>
                </ul>
            {% endif %}
            <!-- show My Blog only if user is authenticated -->
            {% if user.is_authenticated %}
                <ul class="nav navbar-nav ">
                    <li class="active"><a href="{% url 'blog:user_posts' user.username %}">My Blog</a></li>
                </ul>
            {% endif %}
            <!-- show new post only if user is authenticated -->
            {% if user.is_authenticated %}
                <ul class="nav navbar-nav ">
                    <li class="active"><a href="{% url 'blog:create_post' %}">New Post</a></li>
                </ul>
            {% endif %}
            <!-- show sign out only if user is authenticated -->
            {% if user.is_authenticated %}
                <ul class="nav navbar-nav ">
                    <li class="active"><a href="{% url 'logout' %}">Sign Out</a></li>
                </ul>
            {% endif %}
        </div>
    </div>
</nav>

<div id="content">
    {% block content %}{% endblock %}
</div>

<hr>

<!-- footer -->
<div class="container">
    <div class="row">
        <div class="col-sm-12">

            <!-- Logged user info -->
            {% if user.is_authenticated %}
                <p class="text-center">
                    | Logged user: {{ user.username }}
                    | Email: {{ user.email }}
                    | Admin:{{ user.is_superuser }}
                    | <a href="{% url 'logout' %}">Sign Out</a>
                </p>
            {% endif %}

            <div>
                <p class="text-center">&copy; 2017 Bootstrap</p>
            </div>

        </div>
    </div>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
</div>

</body>
</html>

blog/templates/blog/create_comment.html
{% extends "blog/base.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">

                <!-- Form - Blog Comment -->
                <form action="" method="post" class="form-horizontal">

                    {% csrf_token %}

                    <div class="form-group">
                        <div class="col-sm-9">

                            <!-- Errors - body -->
                            {% if form.body.errors %}
                                <label class="alert alert-danger">{{ form.body.errors }}</label>
                            {% endif %}

                            <!-- Form field - body -->
                            <textarea placeholder="Body"
                                      class="form-control"
                                      name="body"
                                      required>
                            </textarea>

                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-9">

                             <!-- Submit button -->
                            <button type="submit" class="btn btn-primary btn-block">Save</button>

                        </div>
                    </div>

                </form>

            </div>
        </div>
    </div>
{% endblock content %}

blog/templates/blog/create_post.html
{% extends "blog/base.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">

                <!-- Form - Blog Post -->
                <form action="" method="post" class="form-horizontal">

                    {% csrf_token %}

                    <div class="form-group">
                        <div class="col-sm-9">

                            <!-- Errors - title -->
                            {% if form.title.errors %}
                                <label class="alert alert-danger">{{ form.title.errors }}</label>
                            {% endif %}

                            <!-- Form field - title -->
                            <input type="text"
                                   placeholder="Title"
                                   class="form-control"
                                   name="title"
                                   value="{{ form.title.value|default:"" }}">

                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-9">

                            <!-- Errors - body -->
                            {% if form.body.errors %}
                                <label class="alert alert-danger">{{ form.body.errors }}</label>
                            {% endif %}

                            <!-- Form fields - body -->
                            <textarea placeholder="Body"
                                      class="form-control"
                                      name="body">{{ form.body.value|default:"" }}</textarea>

                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-9">

                            <!-- Submit button -->
                            <button type="submit" class="btn btn-primary btn-block">Save</button>

                        </div>
                    </div>

                </form>

            </div>
        </div>
    </div>
{% endblock content %}

blog/templates/blog/home.html
{% extends "blog/base.html" %}

{% block content %}
    <div class="container">

        <!-- Show this section only for User Blog view -->
        {% if first_name or last_name %}
            <div class="jumbotron">
                <h1>{{ first_name }} {{ last_name }} - Blog</h1>
            </div>
        {% endif %}

        <!-- Show List of Posts -->
        <div class="starter-template">
            {% for post in posts %}
                <div class="panel">
                    <div class="panel-heading">
                        <h1><a href="{% url 'blog:post' post.pk %}">{{ post.title }}</a></h1>
                        <div> Created {{ post.pub_date }} by <a
                                href="{% url 'blog:user_posts' post.user.username %}">{{ post.user.username }}</a>
                        </div>
                    </div>
                    <h3 class="panel-body"> {{ post.body }}</h3>
                </div>
            {% endfor %}
        </div>

        <!-- Pagination -->
        <div class="pagination">
            {% if posts.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ posts.previous_page_number }}">previous</a>
            {% endif %}

            {% if posts.paginator.num_pages != 1 %}
                Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
            {% endif %}

            {% if posts.has_next %}
                <a href="?page={{ posts.next_page_number }}">next</a>
                <a href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </div>

    </div>
{% endblock content %}

blog/templates/blog/login.html
{% extends "blog/base.html" %}

{% block content %}
    <div class="container">
        <div class="row" style="margin-top:20px">
            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">

                <!-- Errors messages -->
                <div class="col-sm-9">

                    {% if form.errors %}
                        <div class="alert alert-danger">Your username and password didn't match. Please try again.</div>
                    {% else %}
                        {% if next %}
                            {% if user.is_authenticated %}
                                <div class="alert alert-info">Your account doesn't have access to this page. To proceed,
                                    please login with an account that has access.
                                </div>
                            {% else %}
                                <div class="alert alert-info">Please login to see this page.</div>
                            {% endif %}
                        {% endif %}
                    {% endif %}

                </div>

                <!-- Form - Login -->
                <form method="post" action="{% url 'login' %}" class="form-horizontal">

                    {% csrf_token %}

                    <div class="form-group">
                        <div class="col-sm-9">

                            <!-- Form field - username -->
                            <input type="text"
                                   placeholder="Username"
                                   class="form-control"
                                   name="username">

                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-9">

                            <!-- Form field - password -->
                            <input type="password"
                                   placeholder="Password"
                                   class="form-control"
                                   name="password">

                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-9">

                            <input type="submit" class="btn  btn-primary btn-block" value="Login"/>

                        </div>
                    </div>

                    <!-- Form field - next -->
                    <!-- Used to configure redirect after successful login -->
                    <input type="hidden" name="next" value="{% url 'blog:home' %}"/>

                </form>

            </div>
        </div>

    </div>
{% endblock %}

blog/templates/blog/post.html
{% extends "blog/base.html" %}

{% block content %}
    <div class="container">

        <!-- Post -->
        <div class="jumbotron">

            <!-- Post title -->
            <h1>{{ post.title }}</h1>

            <div> Created {{ post.pub_date }} by
                <a href="{% url 'blog:user_posts' post.user.username %}">{{ post.user.username }}</a>
            </div>

            <!-- Post body -->
            <h3>{{ post.body }}</h3>

            <!-- Show Update and Delete button only if User is the owner of the Post -->
            {% if post.user == user %}
                <div class="row">

                    <!-- Delete button -->
                    <a href="{% url 'blog:delete_post' post.pk %}" class="col-md-2 pull-right">
                        <button type="button" class="btn btn-primary btn-block">Delete</button>
                    </a>

                    <!-- Update button -->
                    <a href="{% url 'blog:update_post' post.pk %}" class="col-md-2 pull-right">
                        <button type="button" class="btn btn-primary btn-block">Update</button>
                    </a>

                </div>
            {% endif %}

        </div>

        <h2>Comments:</h2>

        <!-- Comments -->
        {% for comment in comments %}
            <div class="well">

                <div> Created {{ comment.pub_date }} by
                    <a href="{% url 'blog:user_posts' comment.user.username %}">{{ comment.user.username }}</a>
                </div>

                <!-- Comment body -->
                <h3> {{ comment.body }}</h3>

            </div>
        {% endfor %}

        <!-- Show Comment button only if User is authenticated -->
        {% if user.is_authenticated %}

            <!-- Comment button -->
            <a href="{% url 'blog:create_comment' post.pk %}" class="col-md-2 pull-right">
                <button type="button" class="btn btn-primary btn-block">Comment</button>
            </a>

        {% endif %}

    </div>
{% endblock content %}

blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}

{% block content %}
    <div class="container">

        <!-- Form -->
        <form action="" method="post">

            {% csrf_token %}

            <div class="col-sm-9">
                <div class="jumbotron">
                    <h3>Are you sure you want to delete Post: "{{ post.title }}"?</h3>
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-9">

                    <!-- Submit button -->
                    <button type="submit" class="btn btn-primary btn-block">Confirm</button>

                </div>
            </div>

        </form>

    </div>
{% endblock content %}

blog/templates/blog/registration.html
{% extends "blog/base.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">

                <!-- Form - User -->
                <form action="" method="post" class="form-horizontal">

                    {% csrf_token %}

                    <div class="form-group">
                        <div class="col-sm-9">

                            <!-- Errors - username -->
                            {% if form.username.errors %}
                                <label class="alert alert-danger">{{ form.username.errors }}</label>
                            {% endif %}

                            <!-- Form field - username -->
                            <input type="text"
                                   placeholder="Username"
                                   class="form-control"
                                   name="username"
                                   required
                                   value="{{ form.username.value|default:"" }}">

                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-9">

                            <!-- Errors - password -->
                            {% if form.password.errors %}
                                <label class="alert alert-danger">{{ form.password.errors }}</label>
                            {% endif %}

                            <!-- Form field - password -->
                            <input type="password"
                                   placeholder="Password"
                                   class="form-control"
                                   name="password"
                                   required
                                   value="{{ form.password.value|default:"" }}">

                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-9">

                            <!-- Errors - first_name -->
                            {% if form.first_name.errors %}
                                <label class="alert alert-danger">{{ form.first_name.errors }}</label>
                            {% endif %}

                            <!-- Form field - first_name -->
                            <input type="text"
                                   placeholder="First Name"
                                   class="form-control"
                                   name="first_name"
                                   required
                                   value="{{ form.first_name.value|default:"" }}">

                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-9">

                            <!-- Errors - last_name -->
                            {% if form.last_name.errors %}
                                <label class="alert alert-danger">{{ form.last_name.errors }}</label>
                            {% endif %}

                            <!-- Form field - last_name -->
                            <input type="text"
                                   placeholder="Last Name"
                                   class="form-control"
                                   name="last_name"
                                   required
                                   value="{{ form.last_name.value|default:"" }}">

                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-9">

                            <!-- Errors - email -->
                            {% if form.email.errors %}
                                <label class="alert alert-danger">{{ form.email.errors }}</label>
                            {% endif %}

                            <!-- Form field - email -->
                            <input type="text"
                                   placeholder="Email"
                                   class="form-control"
                                   name="email"
                                   required
                                   value="{{ form.email.value|default:"" }}">

                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-9">

                            <!-- Submit button -->
                            <button type="submit" class="btn btn-primary btn-block">Submit</button>

                        </div>
                    </div>

                </form>

            </div>
        </div>
    </div>
{% endblock content %}